import { Currency } from "../types/currency"

export const STORAGE_KEY_CURRENCY = "counter_strike_items_currency"
export const STORAGE_KEY_EXCHANGE_RATES = "exchange_rates"
export const STORAGE_KEY_EXCHANGE_RATES_LAST_FETCHED =
    "exchange_rates_last_fetched"

export const currencySigns: Record<string, string> = {
    USD: "$",
    EUR: "€",
    GBP: "£",
    CNY: "¥",
    JPY: "¥",
    CAD: "$",
    AUD: "$",
    HKD: "$",
    ISK: "kr",
    PHP: "₱",
    DKK: "kr",
    HUF: "Ft",
    CZK: "Kč",
    RON: "lei",
    SEK: "kr",
    IDR: "Rp",
    INR: "₹",
    BRL: "R$",
    RUB: "₽",
    HRK: "kn",
    THB: "฿",
    CHF: "Fr",
    MYR: "RM",
    BGN: "лв",
    TRY: "₺",
    NOK: "kr",
    NZD: "$",
    ZAR: "R",
    MXN: "$",
    SGD: "$",
    ILS: "₪",
    KRW: "₩",
    PLN: "zł",
    AED: "د.إ",
    ARS: "$",
    CLP: "$",
    COP: "$",
    CRC: "₡",
    KWD: "د.ك",
    KZT: "₸",
    PEN: "S/.",
    QAR: "ر.ق",
    SAR: "ر.س",
    TWD: "NT$",
    UAH: "₴",
    UYU: "$",
    VND: "₫",
    GEL: "₾",
    BTC: "₿",
    ETH: "Ξ",
    FET: "FET"
}

export const currencies: Currency[] = [
    { id: "USD", name: "United States Dollar", symbol: "$" },
    { id: "EUR", name: "Euro", symbol: "€" },
    { id: "GBP", name: "British Pound", symbol: "£" },
    { id: "CNY", name: "Chinese Yuan", symbol: "¥" },
    { id: "JPY", name: "Japanese Yen", symbol: "¥" },
    { id: "CAD", name: "Canadian Dollar", symbol: "$" },
    { id: "AUD", name: "Australian Dollar", symbol: "$" },
    { id: "HKD", name: "Hong Kong Dollar", symbol: "$" },
    { id: "ISK", name: "Icelandic Króna", symbol: "kr" },
    { id: "PHP", name: "Philippine Peso", symbol: "₱" },
    { id: "DKK", name: "Danish Krone", symbol: "kr" },
    { id: "HUF", name: "Hungarian Forint", symbol: "Ft" },
    { id: "CZK", name: "Czech Koruna", symbol: "Kč" },
    { id: "RON", name: "Romanian Leu", symbol: "lei" },
    { id: "SEK", name: "Swedish Krona", symbol: "kr" },
    { id: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    { id: "INR", name: "Indian Rupee", symbol: "₹" },
    { id: "BRL", name: "Brazilian Real", symbol: "R$" },
    { id: "RUB", name: "Russian Ruble", symbol: "₽" },
    { id: "HRK", name: "Croatian Kuna", symbol: "kn" },
    { id: "THB", name: "Thai Baht", symbol: "฿" },
    { id: "CHF", name: "Swiss Franc", symbol: "Fr" },
    { id: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { id: "BGN", name: "Bulgarian Lev", symbol: "лв" },
    { id: "TRY", name: "Turkish Lira", symbol: "₺" },
    { id: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { id: "NZD", name: "New Zealand Dollar", symbol: "$" },
    { id: "ZAR", name: "South African Rand", symbol: "R" },
    { id: "MXN", name: "Mexican Peso", symbol: "$" },
    { id: "SGD", name: "Singapore Dollar", symbol: "$" },
    { id: "ILS", name: "Israeli New Shekel", symbol: "₪" },
    { id: "KRW", name: "South Korean Won", symbol: "₩" },
    { id: "PLN", name: "Polish Zloty", symbol: "zł" },
    { id: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ" },
    { id: "ARS", name: "Argentine Peso", symbol: "$" },
    { id: "CLP", name: "Chilean Peso", symbol: "$" },
    { id: "COP", name: "Colombian Peso", symbol: "$" },
    { id: "CRC", name: "Costa Rican Colón", symbol: "₡" },
    { id: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
    { id: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
    { id: "PEN", name: "Peruvian Nuevo Sol", symbol: "S/." },
    { id: "QAR", name: "Qatari Rial", symbol: "ر.ق" },
    { id: "SAR", name: "Saudi Riyal", symbol: "ر.س" },
    { id: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
    { id: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    { id: "UYU", name: "Uruguayan Peso", symbol: "$" },
    { id: "VND", name: "Vietnamese Đồng", symbol: "₫" },
    { id: "GEL", name: "Georgian Lari", symbol: "₾" },
    { id: "BTC", name: "Bitcoin", symbol: "₿" },
    { id: "ETH", name: "Ethereum", symbol: "Ξ" },
    { id: "FET", name: "FET Token", symbol: "FET" }
]
